### ISSUE TITLE
Broken URL in README.md

### ISSUE THREAD

**Issue by cchristelis** [AIFDR/inasafe_data#9]
In the document:
```
Quick Installation Guide
========================

You first need to have [QGIS](http://qgis.org/) installed. Grab your free
copy from [the QGIS download page](http://download/qgis.org).

To install the InaSAFE plugin, use the plugin manager in
[QGIS](http://qgis.org):

  Plugins → Manage and Install Plugins → Get more tab

Then search for "InaSAFE", select it and click the install button.
The plugin will now be added to your plugins menu.

**Note:** You may need to restart QGIS if upgrading from a prior version.
```

The download link, is no longer active: http://download/qgis.org

**Comment by akbargumbira** [comment]
I think it's a typo. It should be http://download.qgis.org

On Fri, Mar 13, 2015 at 9:34 PM, cchristelis <notifications@github.com>
wrote:

> In the document:
>
> Quick Installation Guide
> ========================
>
> You first need to have [QGIS](http://qgis.org/) installed. Grab your free
> copy from [the QGIS download page](http://download/qgis.org).
>
> To install the InaSAFE plugin, use the plugin manager in
> [QGIS](http://qgis.org):
>
>   Plugins → Manage and Install Plugins → Get more tab
>
> Then search for "InaSAFE", select it and click the install button.
> The plugin will now be added to your plugins menu.
>
> **Note:** You may need to restart QGIS if upgrading from a prior version.
>
> The download link, is no longer active: http://download/qgis.org
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AIFDR/inasafe_data/issues/9>.
>



-- 

*-------------------*

*Akbar Gumbira*
*Software Engineer*
*Geospatial, NLP, Data Mining, Machine Learning, Artificial Intelligence*

**Comment by cchristelis** [comment]
thanks @akbargumbira! That looks correct. I'm closing this since it should have been logged in inasafe, not as I see now inasafe_data.
